language: php

sudo: false

services:
  - mysql

php:
  - 7.0
  - 7.1
  - nightly

before_install:
  - bash bin/install-wp-tests.sh test travis '' 127.0.0.1:~travis/.my.cnf latest
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
