language: php

sudo: false

services:
  - mysql

php:
  - 7.0
  - 7.1
  - nightly

before_install:
  - bash bin/install-wp-tests.sh test $MYSQL_USER '$MYSQL_PASSWORD' localhost latest
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
